const presetDisplay=__PRESET_DISPLAY__;
let presets={},lastResult=null,lastInputText=null;
const pretty=value=>JSON.stringify(value,null,2);
const acceptanceLabels={accepted:'受理',rejected:'拒否',schema_invalid:'Schema不正',stale:'Stale',provider_failed:'Provider失敗',cancelled:'キャンセル',superseded:'Superseded',unavailable:'利用不可',request_failed:'実行失敗',client_error:'クライアント失敗'};
const expectationLabels={accepted:'受理されるべき',rejected:'拒否されるべき'};
function selectedId(){return document.getElementById('preset').value}
function selectedMeta(){return presetDisplay[selectedId()]||{label:selectedId(),description:''}}
function resultMeta(caseId){return presetDisplay[caseId]||{label:caseId||'manual',description:''}}
function updatePresetSummary(){const meta=selectedMeta();document.getElementById('presetName').textContent=meta.label;document.getElementById('presetDescription').textContent=meta.description;document.getElementById('caseId').textContent=`case: ${selectedId()}`}
async function init(){presets=await(await fetch('/api/presets')).json();const select=document.getElementById('preset');for(const id of Object.keys(presets)){const meta=presetDisplay[id]||{label:id,description:''};const option=document.createElement('option');option.value=id;option.textContent=meta.label;option.title=`${meta.description} (${id})`;select.appendChild(option)}select.addEventListener('change',load);load()}
function setStatus(text,state=''){document.getElementById('statusbar').className=`statusbar ${state}`.trim();document.getElementById('status').textContent=text}
function load(){document.getElementById('input').value=pretty(presets[selectedId()]);updatePresetSummary();setStatus('入力条件をプリセットから読み込みました。')}
function setKpiState(element,state){element.classList.remove('ok','bad','warn');if(state)element.classList.add(state)}
function clearResultForRun(){lastResult=null;lastInputText=null;document.getElementById('resultEmpty').hidden=false;document.getElementById('resultDetails').hidden=true;document.getElementById('resultCase').textContent='実行中';document.getElementById('acceptance').textContent='実行中';document.getElementById('acceptanceRaw').textContent='-';document.getElementById('expectation').textContent='-';document.getElementById('expectationRaw').textContent='-';document.getElementById('latency').textContent='-';document.getElementById('tokens').textContent='-';setKpiState(document.getElementById('acceptanceKpi'),'');setKpiState(document.getElementById('expectationKpi'),'');document.getElementById('blind').textContent='-';document.getElementById('relation').textContent='-';document.getElementById('acceptanceJson').textContent='-';document.getElementById('full').textContent='-';const empty=document.getElementById('resultEmpty');empty.querySelector('strong').textContent='実行中です';empty.querySelector('span').textContent='前回結果をクリアし、新しい実LLM結果を待っています。';document.querySelectorAll('#resultDetails details').forEach(detail=>{detail.open=false})}
function failureResult(body,code,message,extra={}){return {ok:false,case:body?.name||selectedId()||'manual',expected_acceptance:body?.expected_acceptance??null,actual_acceptance:null,matches_expectation:false,error:{code,message},...extra}}
async function run(){const button=document.getElementById('run');button.disabled=true;const rawInputText=document.getElementById('input').value;let body=null;let executedInputText=rawInputText;clearResultForRun();setStatus('実LLMで検証しています…','running');try{body=JSON.parse(rawInputText);executedInputText=pretty(body);document.getElementById('caseId').textContent=`case: ${body.name||'manual'}`;const response=await fetch('/api/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let data;try{data=await response.json()}catch(error){data={detail:`HTTP ${response.status}: response JSONを読めませんでした`}}if(!response.ok){const message=data.detail||data.error?.message||`HTTP ${response.status}`;const failureData=failureResult(body,'request_failed',message,{http_status:response.status,response_body:data});lastResult=failureData;lastInputText=executedInputText;render(failureData);setStatus('実行に失敗しました。検証データをExportできます。','error');return}lastResult=data;lastInputText=executedInputText;render(data);setStatus(data.ok?'検証が完了しました。':'本番Verifierがfail-closedで停止しました。検証データをExportできます。',data.ok?'done':'error')}catch(error){const message=error instanceof Error?error.message:String(error);const failureData=failureResult(body,'client_error',message);lastResult=failureData;lastInputText=executedInputText;render(failureData);setStatus('実行に失敗しました。検証データをExportできます。','error')}finally{button.disabled=false}}
function render(data){document.getElementById('resultEmpty').hidden=true;document.getElementById('resultDetails').hidden=false;document.getElementById('resultCase').textContent=data.case||'manual';const actual=data.actual_acceptance||data.error?.code||'-';const expected=data.expected_acceptance||null;document.getElementById('acceptance').textContent=acceptanceLabels[actual]||actual;document.getElementById('acceptanceRaw').textContent=actual;document.getElementById('expectation').textContent=expectationLabels[expected]||expected||'-';document.getElementById('expectationRaw').textContent=expected||'-';document.getElementById('latency').textContent=data.timing?`${data.timing.total_latency_ms} ms`:(data.total_latency_ms?`${data.total_latency_ms} ms`:'-');document.getElementById('tokens').textContent=data.tokens?`${data.tokens.total.input_tokens} / ${data.tokens.total.output_tokens}`:'-';setKpiState(document.getElementById('acceptanceKpi'),actual==='accepted'?'ok':actual==='rejected'?'bad':'warn');setKpiState(document.getElementById('expectationKpi'),data.matches_expectation===true?'ok':data.matches_expectation===false?'bad':'');document.getElementById('blind').textContent=pretty(data.blind_observation||data.blind_result||data.error||null);document.getElementById('relation').textContent=pretty(data.relation_observation||data.relation_result||data.error||null);document.getElementById('acceptanceJson').textContent=pretty({semantic_observation:data.semantic_observation,acceptance:data.acceptance,error:data.error});document.getElementById('full').textContent=pretty(data);if(!data.ok){document.querySelector('#resultDetails details').open=true}}
function exportMd(){if(!lastResult||lastInputText===null){setStatus('Exportする実行結果がありません。','error');return}const data=lastResult;const meta=resultMeta(data.case);const markdown=`# ゆら V2 Semantic Verification Lab 検証データ\n\n- プリセット: ${meta.label}\n- case ID: ${data.case}\n- 期待結果: ${data.expected_acceptance??'-'}\n- 実結果: ${data.actual_acceptance??data.error?.code??'-'}\n- エラー: ${data.error?.message??'-'}\n- total latency ms: ${data.timing?.total_latency_ms??data.total_latency_ms??'-'}\n\n## 検証入力\n\`\`\`json\n${lastInputText}\n\`\`\`\n\n## 本番検証結果\n\`\`\`json\n${pretty(data)}\n\`\`\`\n`;const url=URL.createObjectURL(new Blob(['\ufeff',markdown],{type:'text/markdown;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`semantic-verification-${data.case||'export'}.md`;anchor.click();window.setTimeout(()=>URL.revokeObjectURL(url),0);setStatus('実際に実行したcaseの検証データをExportしました。','done')}
document.getElementById('load').addEventListener('click',load);
document.getElementById('run').addEventListener('click',run);
document.getElementById('export').addEventListener('click',exportMd);
init();
