"""#364 Reflectionの候補生成・support観測・closed acceptance境界。"""

from .authority import ReflectionCandidateAuthority
from .contracts import (
    MemoryCandidateProposal,
    ReflectionAcceptancePolicy,
    ReflectionCandidateResult,
    ReflectionCandidateStatus,
    ReflectionContextSnapshot,
    ReflectionEventKind,
    ReflectionRelationHint,
    ReflectionRunResult,
    ReflectionRunTelemetry,
    ReflectionSourceEvidence,
    ReflectionSourceKind,
    ReflectionSupportObservation,
    ReflectionSupportRelation,
    ReflectionTrigger,
    ReflectionTriggerKind,
)
from .operational import (
    ReflectionOperationalError,
    ReflectionOperationalFailureCode,
    ReflectionOperationalPolicy,
    ReflectionOperationalPolicyPort,
    bound_source_excerpt,
    estimate_reflection_context_tokens,
    reflection_source_order_key,
    validate_reflection_context_bounds,
    validate_reflection_proposals_bounds,
    validate_reflection_support_bounds,
)
from .runtime import ReflectionCoordinator, ReflectionProposalPort, ReflectionSupportPort

__all__ = [
    "MemoryCandidateProposal",
    "ReflectionAcceptancePolicy",
    "ReflectionCandidateAuthority",
    "ReflectionCandidateResult",
    "ReflectionCandidateStatus",
    "ReflectionContextSnapshot",
    "ReflectionCoordinator",
    "ReflectionEventKind",
    "ReflectionOperationalError",
    "ReflectionOperationalFailureCode",
    "ReflectionOperationalPolicy",
    "ReflectionOperationalPolicyPort",
    "ReflectionProposalPort",
    "ReflectionRelationHint",
    "ReflectionRunResult",
    "ReflectionRunTelemetry",
    "ReflectionSourceEvidence",
    "ReflectionSourceKind",
    "ReflectionSupportObservation",
    "ReflectionSupportPort",
    "ReflectionSupportRelation",
    "ReflectionTrigger",
    "ReflectionTriggerKind",
    "bound_source_excerpt",
    "estimate_reflection_context_tokens",
    "reflection_source_order_key",
    "validate_reflection_context_bounds",
    "validate_reflection_proposals_bounds",
    "validate_reflection_support_bounds",
]
