imports:
  app: runtime.yaml
  trace: runtime.yaml
  input_receivers: runtime.yaml
  confirmation: runtime.yaml

  character: character.yaml

  speech: speech.yaml
  memory: memory.yaml

  services: services.yaml
  models: models.yaml

  response_generator: application.yaml
  llm_roles: application.yaml
  topic_classifier: application.yaml
  streaming: application.yaml
  plugins: application.yaml
