imports:
  app: runtime.yaml
  trace: runtime.yaml
  input_receivers: runtime.yaml
  confirmation: runtime.yaml

  character: character.yaml

  services: application.yaml
  models: application.yaml
  response_generator: application.yaml
  llm_roles: application.yaml
  speech: application.yaml
  topic_classifier: application.yaml
  memory: application.yaml
  streaming: application.yaml
  plugins: application.yaml
